name: compile_sol

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install solidity compiler
        run: yarn global add solc
      - name: Run a sol-compile script
        run: solcjs --bin --abi futures.sol
      - name: Echo current dir files
        run: |
          yourfilenames=`ls ./*.txt`
          for eachfile in $yourfilenames
          do
            echo $eachfile
          done
